INSERT INTO job_listings (company_name,company_image, job_title, job_summary,job_description, salary, location ,schedule,flex_time, date_posted)
VALUES ('TTEC','https://media.licdn.com/dms/image/C4E0BAQHYwbgJcJTxCg/company-logo_100_100/0/1600194010184?e=1694044800&v=beta&t=bFKOmOPvUcppHiNzK9qAFXfXpXKacNFa43Q3-UKFcO4','Full-Stack developer','Position Summary...Imagine working in an environment where one line of code can make life easier for hundreds of millions of people', 'As a Full Stack Web Developer, you should be comfortable around both front-end and back-end coding languages, and modern development frameworks. You should also be a team player with a knack for visual design and willingness to mentor others on rapidly-evolving web technology.', '$70,000','Toronto','Full-Time','Remote','1 week ago');

INSERT INTO job_listings (company_name,company_image, job_title,job_summary,job_description, salary, location, schedule,flex_time, date_posted)
VALUES ('Simons','https://media.licdn.com/dms/image/C560BAQGUm3JLSio8uw/company-logo_100_100/0/1592510036576?e=1694044800&v=beta&t=DmTZoEABMIfaut3Nb0FrtiDzUjQK7pkb5PMsUn6_YWQ','Sales Associate','Every day, we’re empowered to work together to help our customers make fast, confident planning decisions' ,'Provide high-quality customer service to our clientele. Perform various tasks within the assigned department, such as merchandizing products. Enjoy fashion and interacting with people', '$65,000','Hamilton','Part-Time','On-site','3 days ago' );

INSERT INTO job_listings (company_name,company_image, job_title,job_summary,job_description, salary, location ,schedule,flex_time, date_posted)
VALUES ('United Nations','https://media.licdn.com/dms/image/C4E0BAQGd_5g0zDG5VA/company-logo_100_100/0/1679890370488?e=1694044800&v=beta&t=9zuuKvxlrYzmvy3IrbG1cw8FFqvzuQQjlEpMHp9uBNU' ,'Administrative Assistant','The Human Resources Manager reports to the Senior Human Resources Business Partner and supports 4 facilities', 'Processing of visas for UN official travels. Provides guidance to UN sponsored delegates travelling to SCBD meetings on current visa procedures and responds to related queries. Provides guidance to staff members in response to queries related to visa requirements. Liaises and coordinates extensively with all Embassies/High Commissions regarding regulations/requirements for visas. Verifies correctness of visa application forms issued to staff members for visa applications. ', '$60,000','Windsor','Internship','Hybrid', '1 day ago');

INSERT INTO job_listings (company_name,company_image, job_title,job_summary,job_description, salary, location ,schedule,flex_time, date_posted)
VALUES ('Nations','https://media.licdn.com/dms/image/C4E0BAQGd_5g0zDG5VA/company-logo_100_100/0/1679890370488?e=1694044800&v=beta&t=9zuuKvxlrYzmvy3IrbG1cw8FFqvzuQQjlEpMHp9uBNU' ,'Administrative Assistant','The Human Resources Manager reports to the Senior Human Resources Business Partner and supports 4 facilities', 'Processing of visas for UN official travels. Provides guidance to UN sponsored delegates travelling to SCBD meetings on current visa procedures and responds to related queries. Provides guidance to staff members in response to queries related to visa requirements. Liaises and coordinates extensively with all Embassies/High Commissions regarding regulations/requirements for visas. Verifies correctness of visa application forms issued to staff members for visa applications. ', '$60,000','Oakville','Internship','Hybrid','1 month ago');


