DROP TABLE IF EXISTS projects CASCADE;
CREATE TABLE projects (
  id SERIAL PRIMARY KEY NOT NULL,
  resume_id INTEGER NOT NULL REFERENCES resume(id),
  name VARCHAR(255) NOT NULL,
  project_img VARCHAR(255) NOT NULL,
  project_description VARCHAR(255) NOT NULL
);
