DROP TABLE IF EXISTS education CASCADE;
CREATE TABLE education (
  id SERIAL PRIMARY KEY NOT NULL,
  resume_id INTEGER REFERENCES resumes(id) ON DELETE CASCADE,
  univ_degree VARCHAR(255) NOT NULL
);
